# P419 08 Модули и пакеты

Автор: Шабанов Павел Александрович

Email: pa.shabanov@gmail.com

URL: [Заметки по программированию в науках о Земле](http://progeoru.blogspot.ru/)

**Дата последнего обновления: 28.10.2018**

<a id='up'></a>
### План

1. **[Модули](#modules)**
    + [правила импортирования](#import);
    + [dir()](#dir).
2. **[Модули в других папках. Пакеты](#modules_folders)**
    + [пакеты и файл **\_\_init\_\_.py**](#packages);
    + [if \_\_name\_\_ == 'main':](#valid_import)
    + [имена и пути к функциям в модулях и древах каталогов](#tree).

### Ссылки:

+ Н.А. Прохорёнок "Python самое необходимое", Глава 12 Модули и пакеты, с. 194-206

<a id='modules'></a>
## Модули
[Вверх](#up)

`Модуль` - это программная единица. Программа на python состоит хотя бы из 1 т.н. главного модуля. 

Главный модуль можно определить с помощью особой переменной **\_\_name\_\_**, которую можно вызвать всегда из тела python-скрипта. 

У главного модуля этот параметр имеет значение **'main'**.

In [ ]:
s = __name__
if s == '__main__':
    print(f'Это главный модуль, его имя {s}')
else:
    print(f'Это сторонний модуль, его имя {s}')

Модулем в языке Python может называться любой текстовый файл расширением **.py**. 

Каждый модуль может импортировать другой модуль, получая, таким образом, доступ к содержимому импортированного модуля. Следует заметить, что импортируемый модуль может содержать программу не только на языке Python, но и скомпилированный модуль, написанный на языке Fortran или C.

Любой дистрибутив python поставляется с наобором стандартных модулей (т.н. "батареек"), которые можно использовать всегда. Приведём примеры некоторых модулей, которые встречались нам ранее:

+ **os** - модуль для работы с операционной системой;
+ **time** - модуль для работы со временем;
+ **sys** - модуль для работы с переменными и функциям, взаимодействующими с интерпретатором python;
+ **keyword** - модуль для работы с ключевыми словами языка python;
+ **random** - модуль для работы с псевдослучайными числами.

> **sys.modules - словарь имен загруженных модулей;**

> **sys.path - список путей поиска модулей;**

> **sys.prefix - путь установки интерпретатора Python.**

<a id='import'></a>
### Правила импортирования 
[Наверх](#up)

Импортировать модуль позволяет инструкция **import**.

Общий вид данной инструкции выглядит так:

> **from** MODULE1 **import** FUNCTION_or_CLASS **as** myShortName

После ключевого слова `import` через пробел указывается имя модуля (без расширения и пути к файлу - см. ниже). При именовании модулей выполняются те же правила, что и для всех переменных. Следует избегать совпадения с ключевыми словами, встроенными идентификаторами и названиями модулей, входящих в стандартную библиотеку.

За один раз можно импортировать сразу несколько модулей, перечислив их через запятую.

In [ ]:
import os, sys
import time

print ('Место установки интерпретатора Python: {}'.format(sys.prefix))
print ('А в этих папках Python ищет модули: {}\n'.format(sys.prefix))
for v in sys.path:
    j = sys.path.index(v)
    print(j, v)

При обращение к модулю можно использовать не его имя, а аббревиатуру или псевдоним. Для этого следует использовать ключевое слово **as** в конструкции **import** после имени модуля: 

> **import numpy as np**

> **import pandas as pd**

> **import matplotlib.pyplot as plt**

Также при импорте модуля можно воспользоваться ключевым словом **from** для импортирования только необходимой части модуля. Слово **from** ставится вначале конструкции `import`. Например, *from numpy import random as rr*.

Конструкция `from имя_модуля import *` позволяет импортировать все идентификаторы модуля и обращаться к ним далее без использования точечной нотации. Это неявное импортирование (implicit import), оно не рекомендуется к использованию рядом положений и противоречит принципу python-dzen "Explicit is better than implicit".

In [1]:
# Если при повторном запуске из Jupyter notebook здесь не отображается дзен-python, 
# перегрузите output: Kernel -> Restart & Clear Output

import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [2]:
print(type(this))

<class 'module'>


In [3]:
import sys

import numpy as np   # псевдоним
from numpy import random as rn   # импорт части модуля
from numpy.random import random # импорт функции
from numpy.random import random as randx   # импорт функции под псевдонимом

shapexy = (7, 12)
print('np is a {}'.format(type(np)))
z1 = rn.random(shapexy)
z2 = randx(shapexy)
z3 = random(shapexy)

print(z1[:3, :3])

np is a <class 'module'>
[[0.49195631 0.9050553  0.94362859]
 [0.01433571 0.00729072 0.25012357]
 [0.41842317 0.28322784 0.74256502]]


<a id='dir'></a>
### dir()
[Вверх](#up)

Встроенная функция `dir()` возвращает список имен объекта, а если объект не указан,
то список имен в текущей локальной области видимости.



In [4]:
d = dir()
print(type(d))
ilist = sorted(d)
print(ilist)

# Список без имён переменных с __ и _
b = [s for s in dir() if ('_' not in s)]
print(b)

<class 'list'>
['In', 'Out', '_', '__', '___', '__builtin__', '__builtins__', '__doc__', '__loader__', '__name__', '__package__', '__spec__', '_dh', '_i', '_i1', '_i2', '_i3', '_i4', '_ih', '_ii', '_iii', '_oh', 'exit', 'get_ipython', 'np', 'quit', 'random', 'randx', 'rn', 'shapexy', 'sys', 'this', 'z1', 'z2', 'z3']
['In', 'Out', 'd', 'exit', 'ilist', 'np', 'quit', 'random', 'randx', 'rn', 'shapexy', 'sys', 'this', 'z1', 'z2', 'z3']


<a id='modules_folders'></a>
## Модули в других папках. Пакеты
[Наверх](#up)

Хранить все модули и исходные коды, а также необходимые к ним данные, в одной папке неудобно даже для небольших проектов. 

Чтобы организовать хранение файлов с исходным кодом, функциональные и логичные части кода, оформленные в виде модулей с набором функций и классов, выносят в другие папки, помещают в другие места на компьютере.

Чтобы организовать систему хранения модулей, нужно представлять как python ищет модули при импортировании с помощью конструкции **import**. 

<a id='packages'></a>
### Пакеты и файл __init__.py
[Наверх](#up)

В случае, когда в папке с модулями есть другие папки, также содержащие внутри себя и модули и папки c модулями ("матрёшка"), для доступа к модулям внутри папок необходимо превратить папки в **пакеты (packages)**

**Пакетом** называется папка с python-файлами, в которой также находится особый файл инициализации **\_\_init\_\_.py**. 

> folder4/\_\_init\_\_.py

`Файл инициализации` может быть пустым или содержать код, который будет выполнен при первом обращении к пакету. В любом случае, он обязательно должен быть внутри папки с модулями.

В Листинге "A" представлено две функции непосредственно в теле модуля **ffunc4.py**.

In [ ]:
%%writefile ./folder4/ffunc4.py

# ЛИСТИНГ "А" Пакеты main1

# -*- coding: utf-8 -*-
"""
Created on Fri Mar 11 22:48:27 2016

@author: pasha
"""

import sys
import math
import random
import numpy as np

def haversine(origin, destination):
    '''
    Points are tuples of (latitude, longitude)
    '''
    lat1, lon1 = origin
    lat2, lon2 = destination
    radius = 6371. # km

    dlat = math.radians(lat2-lat1)
    dlon = math.radians(lon2-lon1)
    a = math.sin(dlat/2.) * math.sin(dlat/2.) + math.cos(math.radians(lat1)) \
        * math.cos(math.radians(lat2)) * math.sin(dlon/2.) * math.sin(dlon/2.)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1.-a))
    d = radius * c

    return d

def pirson_cc(x, y):
    u'''
    Это строка документирования!
    Функция вычисляет для двух последовательностей \
    коэффициент корреляции Пирсона.
    
    Входящие параметры:
    ===================
    
    **x [ndarray]** - одномерный массив длины N;
    **y [ndarray]** - одномерный массив длины N;
    
    Результат выполнения функции:
    =============================
    **сс [float]** - коэффициент корреляции Пирсона.
    '''
    
    xm = x.mean()
    ym = y.mean()

    a = 0
    b1 = 0
    b2 = 0
    for xi, yi in zip(x, y):
        a += (xi - xm)*(yi - ym)
        b1 += (xi - xm)**2 
        b2 += (yi - ym)**2
    b = np.sqrt(b1*b2)
    
    cc = float(a)/b
    return cc

# **************************************

N = 60
# методы списка + модуль random
a = list(range(N))
random.shuffle(a)
a = np.array(a)

# модуль numpy
b = np.arange(N)
np.random.shuffle(b)

TSK = (56.49, 84.95)   # 56°29′19″ с. ш. 84°57′08″ в. д.
MSK = (55.76, 37.61)  # 55°45′21″ с. ш. 37°37′04″ в. д.
SPB = (59.95, 30.61) # 59°57′00″ с. ш. 30°19′00″ в. д. (G) (O) (Я)

filename = sys.argv
print((f'Привет! Я файл {filename[0]} и ты видишь это всё,'
       'хотя хотел импортировать лишь одну функцию haversine'))
print ('От Москвы до Ленинграда {:.2f} км'.format(haversine(SPB, MSK)))
print ('CC from def cc: {:.3f}'.format(pirson_cc(a, b)))
print ('\n Сравни: \n')
print ('CC from numpy: {:.3f}'.format(np.corrcoef(a, b)[0][1]))

In [6]:
#%%writefile test_pash4.py

from folder4.ffunc4 import haversine

MSK = (55.76, 37.61)  # 55°45′21″ с. ш. 37°37′04″ в. д.
SPB = (59.95, 30.61) # 59°57′00″ с. ш. 30°19′00″ в. д. (G) (O) (Я)

dist = haversine(SPB, MSK)
print (f'От Питера до Москвы {dist:.2f} км')

Привет! Я файл C:\Users\pasha\Anaconda3\lib\site-packages\ipykernel_launcher.py и ты видишь это всё,хотя хотел импортировать лишь одну функцию haversine
От Москвы до Ленинграда 622.71 км
CC from def cc: 0.024

 Сравни: 

CC from numpy: 0.024
От Питера до Москвы 622.71 км


При первом импорте у нас вместе с импортом функции haversine всплывёт ещё и весь код, которые не является функцией. В том числе и фраза:

> *Привет! Я файл ffunc4.py и ты видишь это всё, хотя хотел импортировать лишь одну функцию haversine!*

При этом объявленные переменные из тела импортированного (например, b) не будут в области видимости главного модуля.

<a id='valid_import'></a>
### if \_\_name\_\_ == 'main':
[Вверх](#up)

Чтобы избежать нежелательного конетента при импортировании, предлагается использовать следующий приём: проверять является ли модуль главным. 

> if \_\_name\_\_ == 'main':

Если да, тогда будет исполняться основное тело скрипта. Если же нет, то всё содержимое скрипта будет проигнорировано.

In [ ]:
def foo1():
    pass

def foo2():
    pass

if __name__ == 'main':
    pass

Сравни содержание ffunc4.py и ffunc42.py

При импорте функции "haversine" из ffunc42.py появления побочного контента не будет.

In [7]:
from folder4.ffunc42 import haversine

MSK = (55.76, 37.61)  # 55°45′21″ с. ш. 37°37′04″ в. д.
SPB = (59.95, 30.61) # 59°57′00″ с. ш. 30°19′00″ в. д. (G) (O) (Я)

dist = haversine(SPB, MSK)
print (f'От Питера до Москвы {dist:.2f} км')

От Питера до Москвы 622.71 км


Если запустить честно файл ffunc4.py из командной строки, то имя файла будет нормальным. В случае же jupyter notebook, происходит "оборачивание", поэтому `sys.argv` выводит на экран что-то иное... 

In [9]:
#%%writefile test_sysargv.py

import sys
s = sys.argv
print(s[0])

Writing test_sysargv.py


<a id='tree'></a>
### Имена и пути к функциям в модулях и древах каталогов.
[Наверх](#up)

Узнать список папок и каталогов, где интерпретатор python ищет модули, позволяет метод **path** модуля **sys (sys.path)**.

In [ ]:
import sys
lst = sys.path
print(type(lst))

for i, s in enumerate(lst):
    print(i+1, s)

Так как sys.path является списком, значит в этот список можно добавить любой элемент (в т.ч. строка).

Для добавления в этот список какой-либо папки следует воспользоваться методом списков *append()*: 

> **sys.path.append(абсолютный путь к папке)**.

In [ ]:
import sys
sys.path.append(r'C:/pylib')

Другой вариант - добавить путь к нужной папке в переменную среды **"PYTHONPATH"**. Для разных ОС процедура добавления переменных среды различается.

Так Spyder позволяет добавить папку в процессе текущей сессии (см. Инструменты -> менеджер PYTHONPATH).

[Вверх](#up)